Repository Activiti/activiti-cloud-app-service, pull requests merged in 2018-11, with the labels that each got.

#44 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.39
  pom.xml
Labels: updatebot

#45 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.41
  pom.xml
Labels: updatebot

#49 update org.activiti.cloud.common:activiti-cloud-service-common-dependencies to 7.0.49
  pom.xml
Labels: in progress, updatebot

#50 Add activiti-cloud-app-dependencies-tests module
  .mergify.yml
  activiti-cloud-app-dependencies/pom.xml
  activiti-cloud-app-service/pom.xml
  dependencies-tests/pom.xml
  pom.xml
Labels: enhancement, in progress

#51 fix(versions): update Activiti/activiti-cloud-app-service versions
  pom.xml
Labels: in progress, updatebot

#52 fix(versions): update Activiti/activiti-cloud-app-service versions
  pom.xml
Labels: in progress, updatebot

#53 fix(versions): update Activiti/activiti-cloud-app-service versions
  pom.xml
Labels: in progress, updatebot

#54 fix(versions): update Activiti/activiti-cloud-app-service versions
  pom.xml
Labels: in progress, updatebot

#55 fix(versions): update Activiti/activiti-cloud-app-service versions
  pom.xml
Labels: in progress, updatebot
